### PR TITLE
feat(api): allow destroying token without client_secret

### PR DESCRIPTION
**Pull request by seanmonstar**
A problem came up that I'm trying to revoke tokens created by implicit grants, so I don't have the client secret available. I looked at Google's API, and they don't require any authorization either (if you already have a token, things gon burn): https://developers.google.com/accounts/docs/OAuth2WebServer#tokenrevoke

@rfk r?

### CODE REVIEW

**Comment by ckarlof** [comment]
I like it. @rfk is on PTO until next week. I don't suspect this is blocking anything, but if it is, we find another reviewer this week.

**Comment by rfk** [comment]
:+1:

**Comment by rfk** [comment]
Although...will we have any clients in the wild that are passing the client_secret to this API.  Perhaps we should accept it and silently ignore it (which may be the default behaviour of hapi anyway, but it's worth thinking about explicitly)

**Comment by seanmonstar** [comment]
@rfk I want to say this does what you said, but I don't know for sure: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/server.js#L30

**Comment by rfk** [comment]
Let's add an explicit test to this effect, just to be sure

**Comment by rfk** [comment]
I filed #202 to follow up on this

**Pull request merged**
