### PR TITLE
chore(logging): Log additional details for debugging expired tokens

### PR DESCRIPTION
**Pull request by rfk**
Adds logging to help diagnose who is using expired tokens in #308.

### CODE REVIEW

**Comment by rfk** [comment]
@jrgm here's a suggestion for getting more details on #308.  It adds logging not only if someone tries to use an expired token, but if someone uses a token that's more than 24 hours old.  This should give us info on reliers that might be burnt by reducing the access_token expiry time in the future.

I haven't added any tests because we're not set up for it; this would be another fine application of the mocking stuff @philbooth added in #305.

Thoughts?

**Comment by jrgm** [comment]
Yeah, haven't run it, but LGTM. Probably should do this in train-42. (I marked some other pending PR to be train-43). Thanks.

**Comment by rfk** [comment]
@seanmonstar r?

**Comment by jrgm** [comment]
r+

**Pull request merged**
