### PR TITLE
fix(openid): Dynamicly generate openid keys 

### PR DESCRIPTION
**Pull request by vbudhram**
This PR adds the ability to generate dynamic OpenId keys which is needed by https://github.com/mozilla/fxa-dev/issues/212. The files, key.json and oldKey.json are created via npm postinstall script. If the environment configuration specifies a `keyPath` or `oldKeyPath`, then these keys will be loaded into the openid configuration.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 409d8c92125c5782ac7d7947633f62638dc01b5c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8c325a545ec042ffa5741c11331b8f9de45d9d0a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by rfk** [comment]
Oh yeah, that's gitcop; it shows up to tell people about our commit-message format guidelines, which are probably best absorbed by just paging through `git log` a little :-)

**Comment by vbudhram** [comment]
Thanks! I forgot about commit message styling, will update.

**Comment by vladikoff** [comment]
@vbudhram this might need a npm shrinkwrap update

**Comment by rfk** [comment]
> this might need a npm shrinkwrap update

More specifically, IIRC we're trying to standardize on `npm shrinkwrap --dev` to ensure that dev dependencies are also covered by the shrinkwrap file.

**Comment by vbudhram** [comment]
Sounds good! Will add shrinkwrap with dev dependencies.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 409d8c92125c5782ac7d7947633f62638dc01b5c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8c325a545ec042ffa5741c11331b8f9de45d9d0a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by vbudhram** [comment]
Took a little longer than I thought to get through npmshrink issues and squashing commits :/, review when you get a chance, @seanmonstar @vladikoff

**Comment by seanmonstar** [comment]
Test failure looks unrelated. Could you do a `git rebase -i origin/master` and squash into a single commit?

**Comment by vbudhram** [comment]
@seanmonstar r?

**Comment by seanmonstar** [comment]
Looks good to me. I believe an accompanying pull request for fxa-dev would be useful. Likely just removing the keys from that repo.

**Pull request merged**
