### PR TITLE
feat(db): add basic migration infrastructure to mysql backend

### LINKED ISSUE #183: DB migration infrastucture
Let's get some DB migration infrastructure in place for this repo, we've now got at least two open issues that could make use of it.  We could consider just copying what's done in https://github.com/mozilla/fxa-auth-db-server as the default option.

### PR DESCRIPTION
**Pull request by rfk**
This is a work-in-progress branch to import the db-patcher functionality from fxa-auth-db-server.  Not ready for merge.

Fixes #183

### CODE REVIEW

**Comment by rfk** [comment]
Alrighty @seanmonstar and @chilts, here's an attempt at adding db migrations to this repo, inspired by the way we do it with mysql-patcher in fxa-auth-db-server.  What do you think?

@chilts, you may notice that I'm cheating and using the private `readDbPatchLevel` function from `mysql-patcher` here.  I think it might be worth doing a new release to expose this properly as a public API since "check current patch level" is something we're now doing in two projects.

I also filed https://github.com/chilts/mysql-patcher/issues/10 re: the use of `multipleStatements=true`.

@seanmonstar, please r? modulo the above mysql-patcher tweaks.

**Comment by rfk** [comment]
I'm going to try this out on a dannybox deployment, but I *think* that the patcher should automagically start working with no change, via the following logic:

  * we use `createSchema: true` on the dannyboxes
  * if there's no `dbMetadata` table, then `mysql-patcher` assumes we're at patch level zero and will apply 000-001 and 001-002 in order
  * 000-001 will create the `dbMetadata` table
  * 001-002 will update the patch level but have no other effect, since the tables already exist

For deployment to prod, ops need only run the same two sets of patches.

**Comment by rfk** [comment]
> I'm going to try this out on a dannybox deployment, but I think that the patcher should automagically start working with no change

I completed this today and it went really well - upgraded from current master, to this PR, to the last-auth-at PR, and the patcher automagically did the right thing at each stage.  I love when things work out.

**Comment by rfk** [comment]
note to self: comment on the use of `IF NOT EXISTS` in patch-001-002 - it's good to use here because the tables already exist, but we should discourage any future patches from using it as they should fail noisily if other tables exist.

**Comment by rfk** [comment]
assigning to @seanmonstar for review

**Comment by rfk** [comment]
mysql-patcher API tweaks in https://github.com/chilts/mysql-patcher/pull/11, and this PR updated to use them.  It's sligthly cleaner, but we could iterate further in subsequent versions.

**Comment by rfk** [comment]
dammit, npm-shrinkwrap....

**Comment by rfk** [comment]
The new version of mysql-patcher has been released, and the API changed cleaned this up alot.  @seanmonstar this is now ready for final review.

**Comment by seanmonstar** [comment]
Hmm, it seems that #205 includes this code, right? I left comments about this code in that PR. I can make them again here if it's difficult to correlate them.

**Comment by rfk** [comment]
> Hmm, it seems that #205 includes this code, right?

It does.  Simplest option may be to just close this and complete review of both over in #205

**Pull request merged**
