### PR TITLE
revert(tokens): dont reject expired tokens, again

### PR DESCRIPTION
**Pull request by rfk**
We ran into some operational issues when deploying this, backing it out
so that we can get the rest of train-53 out the door.

@jrgm r?

### CODE REVIEW

**Comment by rfk** [comment]
Travis failure appears to be this `fxa-oauth-server.db.ERROR: activateDeveloper Error: ER_DUP_ENTRY` that we've seen before, not related to this PR.

**Comment by jrgm** [comment]
r+

**Comment by vladikoff** [comment]
restarted tests

**Comment by jrgm** [comment]
OK. All green now. Merging.

**Pull request merged**
