### PR TITLE
chore(config): Update convict and switch on strict validation.

### LINKED ISSUE #263: set convict to strict validation
This will catch when any config value is added that shouldn't have been, or typos. Requires a bump to convict@0.8

### PR DESCRIPTION
**Pull request by rfk**
Fixes #263

### CODE REVIEW

**Comment by rfk** [comment]
dependency-related travis failures....*shrug*

**Comment by rfk** [comment]
@chilts r?

**Comment by rfk** [comment]
Note that I've disabled the check-for-vulnerable-modules thing since it was failing due to an awsbox dependency, and we don't have an upgrade path for that.  IIRC we disabled that check in other repos anyway, so it seems like the simplest way to remain unblocked here.

**Comment by rfk** [comment]
Actually I take that back - it seems like the approach in this repo is to not include dev dependencies in the shrinkwrap file, which removes the reported vulnerable module.

**Comment by chilts** [comment]
Tests pass locally, Travis is happy, code lgtm. r+

**Pull request merged**
