### PR TITLE
fix(upgrade): update to bluebird 3

### LINKED ISSUE #570: Update to bluebird 3
During the all-hands we found that bluebird 2 doesn't work so well with Hapi 17.

Let's clean up the old bluebird usage and use native Promises before we upgrade

### PR DESCRIPTION
**Pull request by deeptibaghel**
fixes #570

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 2e864685f1b2d8d14bb1790366be78b21bcc3c36
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 2e864685f1b2d8d14bb1790366be78b21bcc3c36
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8384aaf36d9deab1e23f8fcc2d1891f42296ab0f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 2e864685f1b2d8d14bb1790366be78b21bcc3c36
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4bb8ef33a718bec6d54941e2a02ade11f4a6ec76
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 2e864685f1b2d8d14bb1790366be78b21bcc3c36
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e945fe5ae2a3eccbc3e0fdaae65b32576ab68a54
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 2e864685f1b2d8d14bb1790366be78b21bcc3c36
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e945fe5ae2a3eccbc3e0fdaae65b32576ab68a54
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by vladikoff** [comment]
@deeptibaghel please use the following format for the commit messages:

```
fix(<context>): description
```

Example:

```
fix(upgrade): update to bluebird 3
```

Otherwise it will create warnings....

**Comment by vladikoff** [comment]
Closing this for now

**Pull request closed without merging**
