### PR TITLE
fix(dependencies): move fxa-jwtool from dev-dependencies to dependencies

### LINKED ISSUE #345: fxa-jwtool listed in devDependencies, used in lib/routes/token.js.
Ref https://github.com/mozilla/fxa-content-server/issues/3191.

I am seeing this error in our Travis logs:
```
fxa-oauth-server.CRITICAL: uncaughtException Error: Cannot find module 'fxa-jwtool'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mozilla/fxa-content-server/node_modules/fxa-oauth-server/lib/routes/token.js:12:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/mozilla/fxa-content-server/node_modules/fxa-oauth-server/lib/routing.js:53:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

fxa-jwtool is used by lib/routes/token.js, but is listed as a devDependency and not part of npm-shrinkwrap.json.

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes #345

### CODE REVIEW

**Comment by pdehaan** [comment]
Unrelated, but we could use something like https://github.com/nlf/shrinkydink and cut down our npm-shrinkwrap.json files by roughly 40% and probably make diffs a lot less noisy.

**Comment by vladikoff** [comment]
> Unrelated, but we could use something like https://github.com/nlf/shrinkydink and cut down our npm-shrinkwrap.json files by roughly 40% and probably make diffs a lot less noisy.

I'm afraid to tweak the `npm-shrinkwrap.json` file, it already just barely works with various versions of npm heh

**Comment by seanmonstar** [comment]
I **hate** that the shrinkwrap file seems to change formats every time one of us updates it. Apparently we need to sync some sort of npm config, but it's non-obvious what that is.

**Comment by pdehaan** [comment]
@seanmonstar Totally, although I think **shrinkydink** solves all that (by removing the `from` and `resolved` keys).

Before:
```
...
                "jsonpointer": {
                  "version": "1.1.0",
                  "from": "https://registry.npmjs.org/jsonpointer/-/jsonpointer-1.1.0.tgz",
                  "resolved": "https://registry.npmjs.org/jsonpointer/-/jsonpointer-1.1.0.tgz"
                },
                "xtend": {
                  "version": "4.0.0",
                  "from": "https://registry.npmjs.org/xtend/-/xtend-4.0.0.tgz",
                  "resolved": "https://registry.npmjs.org/xtend/-/xtend-4.0.0.tgz"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

After:
```
...
                "jsonpointer": {
                  "version": "1.1.0"
                },
                "xtend": {
                  "version": "4.0.0"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

We'll still see extreme chaos as soon as one person switches to npm@3 and tries regenerating a shrinkwrap file since everything would get flattened.

**Comment by vladikoff** [comment]
I thought `resolved` was an important field

**Comment by pdehaan** [comment]
@vladikoff No clue how important it is or when/if it's used.
It looks like https://github.com/uber/npm-shrinkwrap normalizes the info to be consistent. I think @jrgm was looking into Uber's **npm-shrinkwrap** tool, but wasn't sure if there were any bugs or issues with it.

**Pull request merged**
