### PR TITLE
feat(scripts): Add script to generate an oauth client

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
This is just a little script that makes it easier to generate oauth credentials

**Comment by vladikoff** [comment]
@jbuck have you seen https://github.com/mozilla/fxa-oauth-client ?

**Comment by jbuck** [comment]
@vladikoff nope! I tried it out and you can't register clients on stage / prod though:

```
fxa http POST https://api.accounts.firefox.com/v1/account/login?sendEmailIfUnverified=false
fxa http 200 https://api.accounts.firefox.com/v1/account/login?sendEmailIfUnverified=false
fxa http POST https://api.accounts.firefox.com/v1/certificate/sign
fxa http 200 https://api.accounts.firefox.com/v1/certificate/sign
fxa http POST https://oauth.accounts.firefox.com/v1/authorization
fxa http 200 https://oauth.accounts.firefox.com/v1/authorization
fxa http POST https://oauth.accounts.firefox.com/v1/client
fxa http 404 https://oauth.accounts.firefox.com/v1/client
fxa http POST https://oauth.accounts.firefox.com/v1/destroy
fxa http 200 https://oauth.accounts.firefox.com/v1/destroy
fxa ERR! oauth Unspecified error
fxa ERR! argv [ '/Users/jbuckley/.nvm/versions/node/v4.6.0/bin/node',
fxa ERR! argv   '/Users/jbuckley/Documents/Github/fxa-oauth-client/bin/fxa-oauth.js',
fxa ERR! argv   '-u',
fxa ERR! argv   'jbuckley@mozilla.com',
fxa ERR! argv   '-e',
fxa ERR! argv   'prod',
fxa ERR! argv   'register' ]
fxa ERR! --version 0.1.0
fxa ERR! code 404
fxa ERR! Additional logging details can be found in:
fxa ERR!      /Users/jbuckley/Documents/Github/fxa-oauth-client/fxa-debug.log
```

This is because we block oauth client registrations on stage/prod right?

**Comment by seanmonstar** [comment]
That's correct. Actually, we just don't even add those routes to the server if not dev.

**Comment by seanmonstar** [comment]
So, do we want to close this since there's a client that already exists?

**Comment by vladikoff** [comment]
@seanmonstar I guess we need this, this will be used for prod it seems.

**Comment by jbuck** [comment]
This script generates clients in a manner that lets @jrgm and I easily add clients to the stage & prod databases via copy/paste. I'd like to keep it somewhere handy, but we could just as easily add it to one of our ops repos.

**Comment by vladikoff** [comment]
Up to you! We can merge it here but need style fixed first:

```
Running "eslint:app" (eslint) task
scripts/generate-client.js
   1:24  error  Expected '!==' and instead saw '!='  eqeqeq
   6:21  error  Strings must use singlequote         quotes
  18:12  error  Strings must use singlequote         quotes
  20:12  error  Strings must use singlequote         quotes
  21:14  error  Strings must use singlequote         quotes
  25:12  error  Strings must use singlequote         quotes
  29:12  error  Strings must use singlequote         quotes
  36:12  error  Strings must use singlequote         quotes
✖ 8 problems (8 errors, 0 warnings)

```

**Comment by jbuck** [comment]
Alright, style is fixed up

**Pull request merged**
