### PR TITLE
Hapi 17 updates

### PR DESCRIPTION
**Pull request by vbudhram**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: ba27ff35fd5c8e232b1ec3b7d1a6bd73fe01f0d6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6eb5583b354e0011df65e5ba4b9b591c381e97da
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 16cd3917de280987732c01807789d47559559e38
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: ba27ff35fd5c8e232b1ec3b7d1a6bd73fe01f0d6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6eb5583b354e0011df65e5ba4b9b591c381e97da
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 16cd3917de280987732c01807789d47559559e38
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 326126ddefa50b960dc4d31c073b61991df841c0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: ba27ff35fd5c8e232b1ec3b7d1a6bd73fe01f0d6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6eb5583b354e0011df65e5ba4b9b591c381e97da
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 16cd3917de280987732c01807789d47559559e38
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 326126ddefa50b960dc4d31c073b61991df841c0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by deeptibaghel** [comment]
@vladikoff shall i work further on this.

**Comment by vladikoff** [comment]
Closing this for now

**Pull request closed without merging**
