### PR TITLE
Backout the "service tokens" feature

### PR DESCRIPTION
**Pull request by rfk**
With apologies to @seanmonstar, this backs out the "service tokens" feature from #336.

It turns out that the db migration to drop the "NOT NULL" constraint from "tokens.email" cannot be applied via an online "ALTER TABLE", so applying it in production would lead to significant downtime.

In discussion with @jrgm we decided that rather than burning cycles on figuring out a way to ship it, we should just back out the feature and wait for https://github.com/mozilla/fxa-auth-server/issues/1053 to land.  At that point we can drop the "email" column entirely rather than trying to modify it in-place, an operation that *can* be successfully applied in production without an outage.

There are three commits here.  The first two revert the two commits from #336.  The third adds a new db migration to patch level 13, reversing the change introduced at patch level 11 by #366.  This will ensure our various dev environments wind up with their db in the same state as production.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 0abbccdc60ae34714ed199f641bcfe6d02678ed5
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: 23643298b637f916df09167db19713f4196818d5
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by rfk** [comment]
@GitCop fine, fine, here's the commits with `revert()` blah blah in the proper form...

**Comment by rfk** [comment]
@seanmonstar r? and a patch-release tag please

**Comment by rfk** [comment]
also @jrgm I'd also appreciate an official r? on this from your POV

**Comment by jrgm** [comment]
r+ on the backout. 

Awfully sorry @seanmonstar. 

In the end, after more work with this, it may have been feasible to make this change; but if this column is going to be discarded later it does seem better to not modify it this week, and then have to do the maintenance all over again in another while (note: feasible means acceptable disruption, not no disruption).

**Comment by seanmonstar** [comment]
(╯°□°）╯︵ ┻━┻

**Pull request merged**
