### PR TITLE
chore(dependencies): bump hapi version

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by pdehaan** [comment]
That's a lot of deletions. Did you run shrinkwrap with the `--dev` flag? (or maybe Hapi just removed some dependencies)

**Comment by vladikoff** [comment]
>  Did you run shrinkwrap with the --dev flag?

Ah no, updated with that now.

**Comment by pdehaan** [comment]
I should probably just get into the habit of adding a "shrinkwrap" script to package.json, so we only need to remember to do `npm run shrinkwrap` in each project and it will be consistent and we wouldnt need to remember to use the various flags.

**Comment by rfk** [comment]
thanks @vladikoff!

**Comment by vladikoff** [comment]
Thanks for merging!

**Pull request merged**
