### PR TITLE
[WIP] feat(pairing): Make the FxA settings client "public" so that keys can be requested.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
blocks https://github.com/mozilla/fxa-content-server/pull/6404

### CODE REVIEW

**Comment by rfk** [comment]
FWIW, I think this change makes sense, and I'd also support adding some special logic so that `canGrant: true` clients are also allowed all scopes automatically, rather than having to list them in `allowedScopes`.

**Comment by vladikoff** [comment]
@rfk to change this PR...

**Comment by rfk** [comment]
@shane-tomlinson what's the difference between the "Firefox Accounts" and "Firefox Accounts Settings" reliers here?

On reflection, I don't think we should make this change - fxa-content-server shouldn't need to do anything *on behalf of itself* that requires `publicClient: true`.  Instead, it should be acting on behalf of whatever OAuth client is using the pairing flow, and should send that `client_id` in its requests to the oauth-server.

For initial dev and testing purposes, we can use an existing `client_id` that has the right configuration, such as `22d74070a481bc73` for `"Test Client iOS"`, which is already marked as public and able to request the `oldsync` scope.

**Comment by shane-tomlinson** [comment]
This PR was meant to move the rest of things forward and not for merge to master, I imagine a new client_id for Sync is needed.

> @shane-tomlinson what's the difference between the "Firefox Accounts" and "Firefox Accounts Settings" reliers here?

I have no idea, @vladikoff, any ideas?

**Comment by rfk** [comment]
I'm putting this in the backlog since we don't need it for the pairsona milestone.

**Comment by vladikoff** [comment]
Closing for now, per moving repos

**Pull request closed without merging**
