### PR TITLE
Fix InvalidAssertions Error code

### PR DESCRIPTION
**Pull request by rishibaldawa**
Fixes the InvalidAssertions error code based on discussions in https://github.com/mozilla/fxa-oauth-server/issues/234

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: a8ecd51308c084e0fd807cf7cb38070c775895be
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by rishibaldawa** [comment]
I'd prefer to avoid doing a forced push to update the commit, let me know if you'd still prefer it for a more descriptive commit message

**Comment by rfk** [comment]
Yes please, we're generally fine with force-push updates to PRs as long as they're called out in the comments here.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: b4bf3b6cd47e030f9c3749b0f1594e76d063e1cb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by rishibaldawa** [comment]
Could you give me an example of the commit message with the right format? or even just some more documentation on the commit format would be helpful.

**Comment by rfk** [comment]
Take a look at the commits list for some examples: https://github.com/mozilla/fxa-oauth-server/commits/master

I suggest something like `fix(api): return a 401 in response to an  invalid assertion`.

> even just some more documentation on the commit format would be helpful.

This could certainly be better; I filed #272 to ensure we revisit those docs

**Comment by rfk** [comment]
@rishibaldawa oh, I noticed there's a table of errors codes in ./docs/api.md that would need to be updated as well.

**Comment by rishibaldawa** [comment]
alright. I'll update that with the commit.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: c5137e030444a0f273ddae72ceb09d3c03fec869
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by rishibaldawa** [comment]
┬─┬﻿ ︵ /(.□. \）

**Comment by rishibaldawa** [comment]
┬─┬ノ( º _ ºノ)

**Comment by rishibaldawa** [comment]
Hang on with the merge. I think I changed the wrong test.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: a7e163d81c84b6a510ebcad327c347066858d4e0
  * Your subject line is longer than 100 characters

Guidelines are available at https://github.com/mozilla/fxa-oauth-server

---
This message was auto-generated by https://gitcop.com

**Comment by rfk** [comment]
@rishibaldawa ugh, I'm sorry this gitcop thing is being so annoying, we may need to tweak it to give folks a break after it's already weighed in on their PR

**Comment by rishibaldawa** [comment]
That's okay. I'll add my "learnings" for #272 

I've corrected the test and the error.js file. 

Just for sake of record keeping ( since I did a whole lotta forced pushes), here's the 3 commits : 
1. https://github.com/mozilla/fxa-oauth-server/commit/2781b3a2bb358cfd0bf0feb792db9ab754f82901 - changed the wrong error code. Gets fixed in 3
2. https://github.com/mozilla/fxa-oauth-server/commit/780aaee3bb818c35195acd064a13e24c4e518615 - doc change
3. https://github.com/mozilla/fxa-oauth-server/commit/d0dba7c9a8de8354f882c7c2af2571a702593a2c - actually set the correct error codes

**Comment by rfk** [comment]
assigning to @seanmonstar for r? just to sanity-check that we understood the comments in #234 correctly

**Pull request merged**
